### ISSUE TITLE
version `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by gallexme** [nerves-project/toolchains#22]
tried with ubuntu 14,16 and debian hm :(
happens when it compiles the dependencies
Raspberry PI 1 
LOG:
> /root/.nerves/artifacts/nerves_toolchain_armv6_rpi_linux_gnueabi-linux_x86_64-0.13.0/bin/armv6-rpi-linux-gnueabi-gcc -c -I/root/.nerves/artifacts/nerves_system_rpi-portable-0.20.0/staging/usr/lib/erlang/erts-9.2/include -I/root/.nerves/artifacts/nerves_system_rpi-portable-0.20.0/staging/usr/lib/erlang/lib/erl_interface-3.10.1/include -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -pipe -Os -I/root/.nerves/artifacts/nerves_system_rpi-portable-0.20.0/staging/usr/include -std=gnu99 -o src/uevent.o src/uevent.c
> /root/.nerves/artifacts/nerves_toolchain_armv6_rpi_linux_gnueabi-linux_x86_64-0.13.0/bin/armv6-rpi-linux-gnueabi-gcc: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /root/.nerves/artifacts/nerves_toolchain_armv6_rpi_linux_gnueabi-linux_x86_64-0.13.0/bin/armv6-rpi-linux-gnueabi-gcc)
> Makefile:66: recipe for target 'src/uevent.o' faile

**Comment by gallexme** [comment]
https://github.com/gallexme/test_nerves
build.sh to build it

**Comment by GregMefford** [comment]
I just saw the same error in TravisCI when trying to build the `nerves_examples`: https://travis-ci.org/nerves-project/nerves_examples/jobs/336391893

**Comment by GregMefford** [comment]
Interestingly, the OSX builds don't seem to have this problem: https://travis-ci.org/nerves-project/nerves_examples/jobs/336391897

**Comment by mobileoverlord** [comment]
We also don't see it on circle which is running under linux in a container
https://circleci.com/gh/nerves-project/nerves_system_rpi/243

**Comment by fhunleth** [comment]
This is due to our transition from TravisCI to CircleCI. Travis runs an older Ubuntu or Debian distribution (I forget which), so any shared libraries/compilers that it used would be older versions. Our CircleCI container must have a more recent gcc and glibc.

Fwiw, the toolchains work for me on Ubuntu 16.04.3. I totally believe you that Ubuntu 14 and Debian are broke. @mobileoverlord We have two options to fix this: One is to create a statically linked toolchain and the other is to install an old gcc/glibc on CircleCI. I'll check into the former, since running old versions has it's own set of pain.

**Comment by gallexme** [comment]
ive also tried ubuntu 16.04 if im not wrong @fhunleth 
atleast the newst 16.04 from docker

**Comment by mobileoverlord** [comment]
@gallexme I tested the changes that @fhunleth made and they seem to fix your issue. They will be available once the toolchains finish building and are released. I will re open this and let you know once they are posted. Thanks :)

**Comment by fhunleth** [comment]
@mobileoverlord Thanks for verifying the change and starting the laborious process of making new toolchain releases!
